### ISSUE TITLE
Image not appearing properly in mobile

### ISSUE THREAD

**Issue by solodev-ux** [Joydeycdvs/Bonded#1]
Visiting the repository GitHub page I noticed that the jumbotron background image is getting streched in Mobile 
![Screenshot_20191219-010600_1](https://user-images.githubusercontent.com/59030470/71117536-559c4000-21fc-11ea-973d-0318db124221.jpg) and after some scrolling the image appears in repeat. 
![Screenshot_20191219-010344_1](https://user-images.githubusercontent.com/59030470/71117635-84b2b180-21fc-11ea-87e1-c7e2dd76fa15.jpg)

**Comment by joy-dey** [comment]
@solodev-ux thanks for bringing this to the attention. Will fix it soon :)

**Comment by solodev-ux** [comment]
@joy-dey the issue is still not solved.
